### ISSUE TITLE
Rename

### ISSUE THREAD

**Issue by dcousens** [common-blockchain/cb-node#6]
This repository has a very confusing name.   
Even the package,  `cb-node` doesn't really allude to what it is.

Thoughts on a re-name?

**Comment by dcousens** [comment]
I'm thinking maybe just `cb-api-server` and `cb-api`, along with `cb-api-tester`?

**Comment by jprichardson** [comment]
What's the distinction between `cb-api` and `cb-node-server`?

**Comment by dcousens** [comment]
@jprichardson rather than getting hung up on names.  I'll outline the packages as they stand:

* A client-side convenience module for accessing the HTTP endpoint on a common blockchain API compliant server
* A common blockchain API compliant express router package, with type checking and the (ideally) ability to plug and play data models
* A testing package for checking the client side module is spec. compliant in terms of the data it returns and the behaviour it exhibits

**Comment by rubensayshi** [comment]
+1 for keeping `cb-` prefixes in repos / packages, this is confusing as hell xD

**Comment by dcousens** [comment]
@rubensayshi thoughts on the names?

**Comment by rubensayshi** [comment]
I did not have a problem with the original ones

**Comment by jprichardson** [comment]
I like `cb-api`, simple and concise.

**Comment by dcousens** [comment]
Perhaps `cb-http-client`?

**Comment by jprichardson** [comment]
I like `cb-http-client`/`cb-http-server`.

**Comment by dcousens** [comment]
@jprichardson it just seemed more in line with us separating the specification from the protocol.
Will rename them to the above.

**Comment by dcousens** [comment]
Closing in favour of #7
